[[collection]]
type = "entry"
title = "Cinema Through the Lens of Breathless (1960)" # optional
subtitle = "High On Films" # optional
link = "https://www.highonfilms.com/breathless-1960-movie-jean-luc-godard/" # optional
icon = "https://matcauthon49.github.io/assets/blog/misc/hof.png" # optional