[[collection]]
type = "entry"
title = "Cinema Through the Lens of Breathless (1960)" # optional
subtitle = "High On Films" # optional
link = "https://www.highonfilms.com/breathless-1960-movie-jean-luc-godard/" # optional
icon = "https://79468c92.delivery.rocketcdn.me/wp-content/uploads/2023/11/cropped-64787031a97aaae67c16c987_cropped-logo-mark-colour-01-32x32-1-32x32.png" # optional