[[collection]]
type = "card_simple"
title = "Orality and Literacy"
content = "Walter Ong"

[[collection]]
type = "card_simple"
title = "Otaku: Japan’s Database Animals"
content = "Hiroki Azuma"

[[collection]]
type = "card_simple"
title = "Crazy Like Us: The Globalization of the American Psyche"
content = "Ethan Watters"

[[collection]]
type = "card_simple"
title = "Earth in My Window"
content = "Takashi Murakami, Linda Hoaglund"

[[collection]]
type = "card_simple"
title = "The Spell of the Sensuous"
content = "David Abram"

[[collection]]
type = "card_simple"
title = "SPQR: A History of Ancient Rome"
content = "Mary Beard"

[[collection]]
type = "card_simple"
title = "Welcome to the Desert of the Real"
content = "Slavoj Žižek"

[[collection]]
type = "card_simple"
title = "The Best of Sports Illustrated"
content = "John Bolster"

[[collection]]
type = "card_simple"
title = "Sun and Steel"
content = "Yukio Mishima"

[[collection]]
type = "card_simple"
title = "Twilight of the Idols"
content = "Friedrich Nietzsche"
