[[collection]]
type = "card_simple"
title = "End Zone"
content = "Don Delillo"

[[collection]]
type = "card_simple"
title = "Ficciones"
content = "Borges"


[[collection]]
type = "card_simple"
title = "Van Gogh: The Complete Paintings"
content = "Ingo F. Walther"