[[collection]]
type = "card_simple"
title = "k-punk"
content = "Mark Fisher"

[[collection]]
type = "card_simple"
title = "Infinite Jest"
content = "David Foster Wallace"
date = "always in progress..."

[[collection]]
type = "card_simple"
title = "Mythology"
content = "Edith Hamilton"


