[[collection]]
type = "card_simple"
title = "Either/Or"
content = "Søren Kierkegaard"

[[collection]]
type = "card_simple"
title = "Dialectic of Enlightenment"
content = "Max Horkheimer & Theodor W. Adorno"
